# Generated by Django 3.2.12 on 2023-05-05 10:03

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.BigIntegerField(verbose_name='创建用户')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新用户')),
                ('document_type', models.TextField(max_length=200, verbose_name='材料类别')),
                ('item', models.IntegerField(verbose_name='期数')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('unity', models.CharField(max_length=200, verbose_name='单位')),
                ('pub_date', models.CharField(max_length=200, verbose_name='发布日期')),
                ('version_content', models.TextField(max_length=21844, verbose_name='模块列表')),
                ('writer', models.CharField(max_length=50, verbose_name='撰稿人')),
                ('publisher', models.CharField(default='翁之梅', max_length=200, verbose_name='签发人')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='DocumentAdvice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.BigIntegerField(verbose_name='创建用户')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新用户')),
                ('doc_city', models.CharField(max_length=100, verbose_name='创建单位')),
                ('doc_name', models.CharField(max_length=100, verbose_name='名称')),
                ('doc_time', models.CharField(max_length=200, verbose_name='创建时间')),
                ('doc_content', models.CharField(max_length=200, verbose_name='内容')),
                ('doc_label', models.CharField(max_length=200, verbose_name='标签')),
            ],
            options={
                'verbose_name': '材料建议库',
                'verbose_name_plural': '材料建议库',
                'db_table': 'doc_advice',
            },
        ),
        migrations.CreateModel(
            name='DocumentSelfDefine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.BigIntegerField(verbose_name='创建用户')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新用户')),
                ('document_type', models.CharField(max_length=200, verbose_name='材料类别')),
                ('name', models.CharField(max_length=200, verbose_name='模块名称')),
                ('item', models.IntegerField(verbose_name='期数')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('unity', models.CharField(max_length=200, verbose_name='单位')),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': '自定义材料',
                'verbose_name_plural': '自定义材料',
                'db_table': 'doc_self_mode',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.BigIntegerField(verbose_name='创建用户')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新用户')),
                ('name', models.CharField(max_length=200, verbose_name='材料类型')),
                ('unity', models.CharField(max_length=200, verbose_name='单位')),
            ],
            options={
                'verbose_name': '材料类型',
                'verbose_name_plural': '材料类型',
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='EcData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.BigIntegerField(verbose_name='创建用户')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新用户')),
                ('model_type', models.CharField(max_length=100, verbose_name='模式种类')),
                ('model_city', models.CharField(max_length=100, verbose_name='城市')),
                ('time', models.CharField(max_length=200, verbose_name='起报时间')),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': '模式预报',
                'verbose_name_plural': '模式预报',
                'db_table': 'ec_data',
            },
        ),
        migrations.CreateModel(
            name='LeaderData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.BigIntegerField(verbose_name='创建用户')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新用户')),
                ('name', models.CharField(max_length=20, verbose_name='呈送发对象')),
                ('service_name', models.TextField(max_length=21844, verbose_name='呈报对象')),
                ('service_unity', models.TextField(max_length=21844, verbose_name='发布单位')),
                ('receive_unity', models.TextField(max_length=21844, verbose_name='抄送单位')),
            ],
            options={
                'verbose_name': '呈送发',
                'verbose_name_plural': '呈送发',
                'db_table': 'leader_data',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.BigIntegerField(verbose_name='创建用户')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新用户')),
                ('name', models.CharField(max_length=200, verbose_name='签发人')),
                ('unity', models.CharField(max_length=200, verbose_name='单位')),
            ],
            options={
                'verbose_name': '签发人',
                'verbose_name_plural': '签发人',
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='SelfModule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.BigIntegerField(verbose_name='创建用户')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新用户')),
                ('document_type', models.CharField(max_length=200, verbose_name='材料类别')),
                ('name', models.CharField(max_length=200, verbose_name='模块名称')),
                ('item', models.IntegerField(verbose_name='期数')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('unity', models.CharField(max_length=200, verbose_name='单位')),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': '个人模块',
                'verbose_name_plural': '个人模块',
                'db_table': 'self_module',
            },
        ),
        migrations.CreateModel(
            name='SelfPlot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.BigIntegerField(verbose_name='创建用户')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新用户')),
                ('document_type', models.CharField(max_length=200, verbose_name='材料类别')),
                ('time', models.CharField(max_length=200, verbose_name='时间')),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': '自定义画图',
                'verbose_name_plural': '自定义画图',
                'db_table': 'self_plot',
            },
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.BigIntegerField(verbose_name='创建用户')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新用户')),
                ('name', models.CharField(max_length=200, verbose_name='单位')),
            ],
            options={
                'verbose_name': '单位',
                'verbose_name_plural': '单位',
                'db_table': 'unity',
            },
        ),
        migrations.CreateModel(
            name='WebClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.BigIntegerField(verbose_name='创建用户')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新用户')),
                ('name', models.CharField(max_length=200, verbose_name='类别')),
                ('unity', models.TextField(max_length=21844, verbose_name='单位')),
            ],
            options={
                'verbose_name': '网站分类',
                'verbose_name_plural': '网站分类',
                'db_table': 'web_class',
            },
        ),
        migrations.CreateModel(
            name='WebPicture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.BigIntegerField(verbose_name='创建用户')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新用户')),
                ('img', models.ImageField(upload_to='web/')),
                ('name', models.CharField(max_length=200, verbose_name='网站名称')),
                ('url', models.CharField(max_length=200, verbose_name='网站地址')),
                ('unity', models.TextField(max_length=21844, verbose_name='单位')),
                ('web_class', models.TextField(max_length=21844, verbose_name='类别')),
            ],
            options={
                'verbose_name': '网站图片',
                'verbose_name_plural': '网站图片',
                'db_table': 'web_picture',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.BigIntegerField(verbose_name='创建用户')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新用户')),
                ('name', models.CharField(max_length=200, verbose_name='撰稿人')),
                ('unity', models.CharField(max_length=200, verbose_name='单位')),
            ],
            options={
                'verbose_name': '撰稿人',
                'verbose_name_plural': '撰稿人',
                'db_table': 'writer',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('role_type', models.IntegerField(default=0, verbose_name='1、领导 2、高工 3、预报员')),
                ('company_name', models.CharField(max_length=50, verbose_name='单位名称')),
                ('company_type', models.IntegerField(default=1, verbose_name='1、省 2、县 3、市')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
